# Config Swagger
app:
  swagger:
    server-url: ${NOTIFICATION_SERVER_URL:https://traefikdev.yowyob.com/notification}

spring:
  application:
    name: notification-service
  profiles:
    active: local

  # 1. CONFIGURATION R2DBC (Réactif - Pour le code Java)
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:notification}
    username: ${DB_USERNAME:notification}
    password: ${DB_PASSWORD:notification}
    pool:
      enabled: true
      initial-size: 1
      max-size: 5

  # 2. CONFIGURATION JDBC (Bloquant - Uniquement pour Liquibase)
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:notification}
    username: ${DB_USERNAME:notification}
    password: ${DB_PASSWORD:notification}
    driver-class-name: org.postgresql.Driver

  # 3. ACTIVATION LIQUIBASE
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    # On peut définir un schéma spécifique si besoin (ex: public ou notification)
    default-schema: public

  # 4. DESACTIVATION DE L'ANCIEN SYSTÈME
  sql:
    init:
      mode: never # On n'utilise plus schema.sql

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification_group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Custom Config (inchangé pour l'instant)
application:
  kafka:
    topics:
      notification-events: notification-topic

springdoc:
  swagger-ui:
    path: /swagger-ui.html
