spring:
  application:
    name: notificaton
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:172.17.0.2}:${DB_PORT:5432}/${DB_NAME:notification}
    username: ${DB_USERNAME:notification}
    password: ${DB_PASSWORD:notification}
    pool:
      enabled: true
      initial-size: 1
      max-size: 5
      max-idle-time: 30m
      max-life-time: 10m
      acquire-retry: 3
      max-acquire-time: 30s
      validation-query: SELECT 1
  sql:
    init:
      mode: always # always | embedded | never
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:168.119.122.86:9092}
    consumer:
      group-id: notification_group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# CUSTOM CONFIG
application:
  kafka:
    topics:
      notification-events: notification-topic

springdoc:
  swagger-ui:
    path: /swagger-ui.html
